<a href="https://colab.research.google.com/github/LeylahfrA01178568/2039_data_visualization/blob/main/A4_pivot_tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Leylah Fragoso Carvajal

## `Activity 4: Pivot tables`

In [12]:
import pandas as pd
import numpy as np

In [13]:
antropometría_path = 'https://raw.githubusercontent.com/tec03/Datasets/refs/heads/main/datasets/antropometria-dataset.csv'

In [15]:

df_antro = pd.read_csv(antropometría_path)
df_antro.head(5)

,folio,intp,entidad,desc_ent,sexo,edad,meses,peso,ropa,talla,...,hpresion,tbrazo,htension,PrimaryLast,code_upm,est_dis,est_urb,est_marg,pondef,est_var
0,210295,2,21,PUEBLA,2,38,8,73.70,2,146.4,...,16:30,2,16:35,1,R2101,5,3,1,3470.002176,215
1,101655,3,10,DURANGO,2,11,11,35.65,2,145.1,...,15:25,3,15:25,1,M1041,1,1,1,417.946672,101
2,10287,6,1,AGUASCALIENTES,2,18,8,54.80,1,162.0,...,9:40,1,9:40,1,M0108,5,3,1,472.980811,15
3,91526,4,9,DISTRITO FEDERAL,1,10,8,33.40,2,146.5,...,7:40,3,7:45,1,M0931,4,3,2,1832.581391,94
4,210939,3,21,PUEBLA,2,19,3,97.95,2,161.0,...,6:00,2,6:00,1,M2123,5,3,1,7622.066564,215

In [23]:
df_antro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18640 entries, 0 to 18639
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   folio        18640 non-null  int64
 1   intp         18640 non-null  int64
 2   entidad      18640 non-null  int64
 3   desc_ent     18640 non-null  object
 4   sexo         18640 non-null  int64
 5   edad         18640 non-null  int64
 6   meses        18640 non-null  int64
 7   peso         18640 non-null  float64
 8   ropa         18640 non-null  int64
 9   talla        18640 non-null  float64
 10  emb          18640 non-null  object
 11  temb         18640 non-null  object
 12  cintura      18032 non-null  float64
 13  cadera       18032 non-null  float64
 14  sistol       18640 non-null  float64
 15  diastol      18640 non-null  float64
 16  hpresion     18640 non-null  object
 17  tbrazo       18640 non-null  object
 18  htension     18640 non-null  object
 19  PrimaryLast  18640 non-null  int64
 20  code_upm     18640 non-null  object
 21  est_dis      18640 non-null  int64
 22  est_urb      18640 non-null  int64
 23  est_marg     18640 non-null  int64
 24  pondef       18640 non-null  float64
 25  est_var      18640 non-null  int64
dtypes: float64(7), int64(12), object(7)
memory usage: 3.7+ MB

### 1. `Pivot table` showing average weight of people per state

In [19]:
# average weight (peso) by state (desc_ent)
pivot_weight_by_state = pd.pivot_table(
    df_antro,
    values='peso',
    index='desc_ent',
    aggfunc='mean'
)


display(pivot_weight_by_state)

                                      peso
desc_ent
AGUASCALIENTES                   66.357786
BAJA CALIFORNIA                  68.467270
BAJA CALIFORNIA SUR              71.809198
CAMPECHE                         65.418475
CHIAPAS                          57.613775
CHIHUAHUA                        66.656005
COAHUILA DE ZARAGOZA             68.154142
COLIMA                           68.743648
DISTRITO FEDERAL                 65.119273
DURANGO                          66.354922
GUANAJUATO                       63.936390
GUERRERO                         60.466315
HIDALGO                          59.995917
JALISCO                          66.697270
MEXICO                           60.680850
MICHOACAN DE OCAMPO              64.900000
MORELOS                          63.541295
NAYARIT                          66.541827
NUEVO LEON                       67.239853
OAXACA                           58.800067
PUEBLA                           60.102996
QUERETARO                        63.547342
QUINTANA ROO                     64.238904
SAN LUIS POTOSI                  60.576912
SINALOA                          68.051272
SONORA                           68.849473
TABASCO                          66.554701
TAMAULIPAS                       68.210911
TLAXCALA                         62.085398
VERACRUZ DE IGNACIO DE LA LLAVE  62.546117
YUCATAN                          62.706315
ZACATECAS                        64.238524

### `sex variable`

Understanding that the sexo variable is a categorical value, sex 1 and 2

In [31]:

sex_count = df_antro['sexo'].value_counts()
display(sex_count) # it has descrete values, identify the type of values

sexo
2    10486
1     8154
Name: count, dtype: int64

In [39]:

df_sex_weight_table = pd.pivot_table(
    df_antro,
    values='peso',
    index='desc_ent',
    columns='sexo',
    aggfunc='mean'
)

display(df_sex_weight_table)

sexo                                     1          2
desc_ent
AGUASCALIENTES                   69.985381  63.254292
BAJA CALIFORNIA                  71.391818  65.893667
BAJA CALIFORNIA SUR              75.561015  68.168959
CAMPECHE                         68.622637  62.920493
CHIAPAS                          58.365222  57.096111
CHIHUAHUA                        68.892642  64.815295
COAHUILA DE ZARAGOZA             68.873094  67.467348
COLIMA                           70.998878  66.978393
DISTRITO FEDERAL                 69.460661  61.654128
DURANGO                          68.846451  64.400031
GUANAJUATO                       65.008000  63.100995
GUERRERO                         62.611437  58.899850
HIDALGO                          61.747958  58.972554
JALISCO                          67.076482  66.418111
MEXICO                           63.140314  58.887882
MICHOACAN DE OCAMPO              66.374612  63.784311
MORELOS                          65.741943  62.195391
NAYARIT                          68.822143  64.890564
NUEVO LEON                       70.168106  64.823014
OAXACA                           60.810332  57.450557
PUEBLA                           61.866875  58.820175
QUERETARO                        66.751233  60.860793
QUINTANA ROO                     65.149528  63.538000
SAN LUIS POTOSI                  62.614907  58.979163
SINALOA                          71.122911  65.565234
SONORA                           70.880406  67.024857
TABASCO                          69.255801  64.190187
TAMAULIPAS                       72.060601  64.866851
TLAXCALA                         64.784437  60.201164
VERACRUZ DE IGNACIO DE LA LLAVE  65.324094  60.565646
YUCATAN                          65.717541  60.537515
ZACATECAS                        66.096483  62.757788

#### Top 5 states with higher average weight per  gender

In [43]:
# Used .nlargest() to obtain directly the highest values
print("Top 5 Estados - Sexo 1 (Hombres):")
display(df_sex_weight_table[1].nlargest(5))

print("\nTop 5 Estados - Sexo 2 (Mujeres):")
display(df_sex_weight_table[2].nlargest(5))

Top 5 Estados - Sexo 1 (Hombres):

desc_ent
BAJA CALIFORNIA SUR    75.561015
TAMAULIPAS             72.060601
BAJA CALIFORNIA        71.391818
SINALOA                71.122911
COLIMA                 70.998878
Name: 1, dtype: float64

Top 5 Estados - Sexo 2 (Mujeres):

desc_ent
BAJA CALIFORNIA SUR     68.168959
COAHUILA DE ZARAGOZA    67.467348
SONORA                  67.024857
COLIMA                  66.978393
JALISCO                 66.418111
Name: 2, dtype: float64

In [44]:
# Used .nsmallest() to obtain directly the lowest values
print("Top 5 Estados - Sexo 1 (Hombres):")
display(df_sex_weight_table[1].nsmallest(5))

print("\nTop 5 Estados - Sexo 2 (Mujeres):")
display(df_sex_weight_table[2].nsmallest(5))

Top 5 Estados - Sexo 1 (Hombres):

desc_ent
CHIAPAS     58.365222
OAXACA      60.810332
HIDALGO     61.747958
PUEBLA      61.866875
GUERRERO    62.611437
Name: 1, dtype: float64

Top 5 Estados - Sexo 2 (Mujeres):

desc_ent
CHIAPAS     57.096111
OAXACA      57.450557
PUEBLA      58.820175
MEXICO      58.887882
GUERRERO    58.899850
Name: 2, dtype: float64

In [81]:

print('El estado con el peso promedio más bajo en sexo 1 es:\n', df_sex_weight_table[1].nsmallest().index[0])

El estado con el peso promedio más bajo en sexo 1 es:
 CHIAPAS

In [76]:
display(df_sex_weight_table[1].nsmallest(1))

desc_ent
CHIAPAS    58.365222
Name: 1, dtype: float64

### Quiz questions antropometria file

#### average weight fos sinaloa

In [57]:
# average weight for sinaloa
av_sinaloa = pivot_weight_by_state.loc['SINALOA']
print('The average weight of Sinaloa is \n', av_sinaloa)

The average weight of Sinaloa is
 peso    68.051272
Name: SINALOA, dtype: float64

#### Median weght for sex 2 in Yucatan

In [63]:
#Median weight(peso) of sex2 of  YUCATAN es :
yucatan_median_pivot_table = pd.pivot_table(
    df_antro,
    values='peso',
    index='desc_ent',
    columns='sexo',
    aggfunc='median'
)
yucatan_median_pivot_table

sexo                                   1        2
desc_ent
AGUASCALIENTES                   69.9500  63.7000
BAJA CALIFORNIA                  70.6500  64.2000
BAJA CALIFORNIA SUR              76.6500  68.5500
CAMPECHE                         67.3500  62.3750
CHIAPAS                          59.2000  56.0250
CHIHUAHUA                        69.3000  64.6250
COAHUILA DE ZARAGOZA             68.3000  67.3000
COLIMA                           71.7000  66.0000
DISTRITO FEDERAL                 69.0000  61.4500
DURANGO                          70.3500  62.5000
GUANAJUATO                       65.0625  60.3250
GUERRERO                         60.5000  57.2000
HIDALGO                          63.3000  57.9000
JALISCO                          65.5875  63.3500
MEXICO                           62.4500  56.9500
MICHOACAN DE OCAMPO              67.6250  63.4000
MORELOS                          65.2000  61.4500
NAYARIT                          69.0500  63.7000
NUEVO LEON                       69.4000  65.1000
OAXACA                           59.5500  56.8000
PUEBLA                           61.8750  59.5500
QUERETARO                        65.2750  59.4500
QUINTANA ROO                     65.9250  60.8500
SAN LUIS POTOSI                  62.2000  57.4500
SINALOA                          71.1000  64.3000
SONORA                           72.3000  66.6500
TABASCO                          69.7500  62.6000
TAMAULIPAS                       72.7500  63.3500
TLAXCALA                         64.2750  59.8750
VERACRUZ DE IGNACIO DE LA LLAVE  64.3000  59.4725
YUCATAN                          66.0000  59.5750
ZACATECAS                        65.3000  61.6250

In [64]:
df_yucatan_2 = yucatan_median_pivot_table.loc['YUCATAN']
df_yucatan_2

sexo
1    66.000
2    59.575
Name: YUCATAN, dtype: float64

In [69]:
median_sex2 = df_yucatan_2.iloc[1]
print(' The median weight for sex 2 in Yucatan is \n', median_sex2)

 The median weight for sex 2 in Yucatan is
 59.575

#### Estado con promedio del peso del sexo1 más bajo.

### 2. `Pivot table`  number of people by each marital status.

In [46]:
adultos_path ='https://raw.githubusercontent.com/tec03/Datasets/refs/heads/main/datasets/adult.csv'

In [47]:
df_adult = pd.read_csv(adultos_path)
df_adult.head(5)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,the label
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

## Create a pivot table by cpunting de number of ages registered, adn then divide per marital status

In [50]:

pivot_marital_status = pd.pivot_table(
    df_adult,
    values='age',
    index='marital-status',
    aggfunc='count'
).rename(columns={'age': 'Number of People'})

display(pivot_marital_status)

                       Number of People
marital-status
Divorced                           4443
Married-AF-spouse                    23
Married-civ-spouse                14976
Married-spouse-absent               418
Never-married                     10683
Separated                          1025
Widowed                             993
test_category_female                  1
test_category_male                    2

### Percentage column


Add a column showing the percentage of people by each marital status.

In [89]:
pivot_marital_status = pd.pivot_table(
    df_adult,
    values='age',
    index='marital-status',
    aggfunc='count'
).rename(columns={'age': 'Number of People'})
pivot_marital_status

                       Number of People
marital-status
Divorced                           4443
Married-AF-spouse                    23
Married-civ-spouse                14976
Married-spouse-absent               418
Never-married                     10683
Separated                          1025
Widowed                             993
test_category_female                  1
test_category_male                    2

In [54]:
percent= (pivot_marital_status['Number of People'] / pivot_marital_status['Number of People'].sum()) * 100

In [55]:

pivot_marital_status['Percentage (%)'] = percent

display(pivot_marital_status)

                       Number of People  Percentage (%)
marital-status
Divorced                           4443       13.643901
Married-AF-spouse                    23        0.070630
Married-civ-spouse                14976       45.989436
Married-spouse-absent               418        1.283626
Never-married                     10683       32.806166
Separated                          1025        3.147648
Widowed                             993        3.049380
test_category_female                  1        0.003071
test_category_male                    2        0.006142

### Quiz questions adult file

#### What is the average age of Divorced with HS-grad?

In [106]:
marital_stat_education = pd.pivot_table(
    df_adult,
    values='age',
    index=['education', 'marital-status'],
    aggfunc='mean'
)
marital_stat_education

                                          age
education    marital-status
10th         Divorced               44.133333
             Married-civ-spouse     46.126074
             Married-spouse-absent  42.000000
             Never-married          23.961219
             Separated              39.530612
...                                       ...
Some-college Married-civ-spouse     42.210433
             Married-spouse-absent  37.289474
             Never-married          25.677804
             Separated              38.086364
             Widowed                57.523256

[103 rows x 1 columns]

In [107]:

hs_grad = marital_stat_education.loc['HS-grad', :]
hs_grad

                             age
marital-status
Divorced               42.363918
Married-AF-spouse      34.615385
Married-civ-spouse     42.817131
Married-spouse-absent  39.413223
Never-married          28.533506
Separated              38.266010
Widowed                59.405797
test_category_female   52.000000
test_category_male     52.000000

In [108]:
hs_grad_divorced = hs_grad.loc['Divorced']
hs_grad_divorced

age    42.363918
Name: Divorced, dtype: float64

####  `'median' 'hours-per-week' of 'Male' 'Married-AF-spouse' with education 'Bachelors'`

In [114]:
pivot_marital_status_sex_hours = pd.pivot_table(
    df_adult,
    values=['age', 'hours-per-week'],
    index=['marital-status','education'],
    columns='sex',
    aggfunc='median'
)
pivot_marital_status_sex_hours

                                     age       hours-per-week
sex                               Female  Male         Female  Male
marital-status       education
Divorced             10th           45.0  39.0           40.0  40.0
                     11th           41.0  38.0           40.0  40.0
                     12th           41.0  41.0           40.0  40.0
                     1st-4th        64.0  63.0           28.0  40.0
                     5th-6th        53.0  56.0           40.0  40.0
...                                  ...   ...            ...   ...
Widowed              Preschool      52.5  71.0           30.0  10.0
                     Prof-school    68.0  42.5           20.0  45.0
                     Some-college   58.0  60.5           40.0  40.0
test_category_female HS-grad        52.0   NaN           40.0   NaN
test_category_male   HS-grad         NaN  52.0            NaN  40.0

[103 rows x 4 columns]

In [119]:

quiz_answer = pivot_marital_status_sex_hours.loc[('Married-AF-spouse', 'Bachelors'), ('hours-per-week','Male')]
quiz_answer

np.float64(50.0)

In [120]:
print('The median hours per week in married af spouses, with bachelors education is \n', quiz_answer)

The median hours per week in married af spouses, with bachelors education is
 50.0